=== kotlasrinivasreddy/xml-dataware-house-operations/dimcust.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:target="http://www.w3schools.com/dimCust" 
                           targetNameSpace="http://www.w3schools.com/dimCust" elementFormDefault="qualified">
    <xs:element name="DimCustomer">
    
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Customer-collection"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:key name="Customer-key">
        <xs:selector xpath="Customer-collection/customer"/>
        <xs:field xpath="CustomerID"/>
    </xs:key>

    </xs:element>
        <xs:element name="Customer-collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="customer" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="customer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CustomerID" minOccurs="1" maxOccurs="1" />
                <xs:element ref="CustomerAltID" minOccurs="1"/>
                <xs:element ref="CustomerName"/>
                <xs:element ref="Gender"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CustomerID" type="xs:decimal"/>
    <xs:element name="CustomerAltID" type="xs:string"/>
    <xs:element name="CustomerName" type="xs:string"/>
    <xs:element name="Gender" type="xs:string"/>

</xs:schema>

=== kotlasrinivasreddy/xml-dataware-house-operations/dimcust.xml
<DimCustomer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/srinivas/Music/dimcust.xsd">
    
    <Customer-collection>

        <customer>
            <CustomerID>1</CustomerID>
            <CustomerAltID>IMI-001</CustomerAltID>
            <CustomerName>Henry Ford</CustomerName>
            <Gender>M</Gender>
        </customer>

        <customer>
            <CustomerID>2</CustomerID>
            <CustomerAltID>IMI-002</CustomerAltID>
            <CustomerName>Bill Gates</CustomerName>
            <Gender>M</Gender>
        </customer>

        <customer>
            <CustomerID>3</CustomerID>
            <CustomerAltID>IMI-003</CustomerAltID>
            <CustomerName>Muskan Shaikh</CustomerName>
            <Gender>F</Gender>
        </customer>

        <customer>
            <CustomerID>4</CustomerID>
            <CustomerAltID>IMI-004</CustomerAltID>
            <CustomerName>Richard Thrubin</CustomerName>
            <Gender>M</Gender>
        </customer>
        
        <customer>
            <CustomerID>5</CustomerID>
            <CustomerAltID> IMI-005 </CustomerAltID>
            <CustomerName>Emma Watson</CustomerName>
            <Gender>F</Gender>
        </customer>
    
    </Customer-collection>
</DimCustomer>
