=== kotlasrinivasreddy/xml-dataware-house-operations/FactProductSales.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                          xmlns:target="http://www.w3schools.com"
                          targetNamespace="http://www.w3schools.com"
                          xml:dimProd="http://www.w3schools.com/dimProd" 
                          xml:dimStores="http://www.w3schools.com/dimStores" 
                          xml:dimCust="http://www.w3schools.com/dimCust" elementFormDefault="qualified">

  <xsd:import namespace="http://www.w3schools.com/dimProd" schemaLocation="dimProd.xsd"/>
  <xsd:import namespace="http://www.w3schools.com/dimStores" schemaLocation="DimStores.xsd"/>
  <xsd:import namespace="http://www.w3schools.com/dimCust" schemaLocation="dimcust.xsd"/>
  
	<xsd:element name="FactProductSales">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="ProductSales-collection"/>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:key name="ProductSales-key">
      <xsd:selector xpath="ProductSales-collection/ProductSale"/>
      <xsd:field xpath="transaction_id"/>
  </xsd:key>
		
		<!--
    <xs:keyref name="dim_cust_ref_key" refer="dimCust:DimCustomer/Customer-key">
      <xs:selector xpath="Customer-collection/customer"/>
      <xs:field xpath="customerId"/>
    </xs:keyref>
    -->
    

    <xsd:keyref name="dim_prod_ref_key" refer="dimProd:DimProd/prod_key"/>
    
	</xsd:element>
	
	<xsd:element name="ProductSales-collection">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="ProductSale" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="ProductSale">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="transaction_id"/>
				<xsd:element ref="store_id"/>
				<xsd:element ref="customer_id"/>
				<xsd:element ref="product_id"/>
				<xsd:element ref="quantity"/>
				<xsd:element ref="sales_total_cost"/>
				<xsd:element ref="product_actual_cost"/>
				<xsd:element ref="deviation"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="transaction_id" type="xs:integer"/>
	<xsd:element name="store_id" type="xs:integer"/>
	<xsd:element name="customer_id" type="xs:integer"/>
	<xsd:element name="product_id" type="xs:integer"/>
	<xsd:element name="quantity" type="xs:integer"/>
	<xsd:element name="sales_total_cost" type="xs:decimal"/>
	<xsd:element name="product_actual_cost" type="xs:decimal"/>
	<xsd:element name="deviation" type="xs:decimal"/>
	
</xsd:schema>



<!--

foreign key:
1. xpath = "./" -> directly giving diff file paths in xpath of xs:selector and xs:field 
2. using different namespace prefixes
3. 

combining primary key:
1. 
2. 

		<xs:key name="auth-key">  -> primary key name.
			<xs:selector xpath="author-collection/author"/> -> primary key collection 
			<xs:field xpath="author-id"/>   -> primary key field name.
		</xs:key>

		<xs:keyref name="auth-ref" refer="auth-key">   -> name: foreign key name. auth-key: is primary key.
			<xs:selector xpath="book-collection/book"/> 	-> xpath: foreign key collection name
			<xs:field xpath="author-ref"/> 	-> xpath: foreign key field name
		</xs:keyref>
		
		
		1. how to combine multiple foreign keys as 1 unique / primary key
		2. foreign key representations - namespace for primary key table or foreign key table.
		3. 
-->

=== kotlasrinivasreddy/xml-dataware-house-operations/factProductSales.xml
<FactProductSales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator" 
    xsi:schemaLocation="/home/srinivas/Music/FactProductSales.xsd">

    <ProductSales-collection>
        <ProductSale>
            <transaction_id>1</transaction_id>
            <store_id>1</store_id>
            <customer_id>1</customer_id>
            <product_id>1</product_id>
            <quantity>4</quantity>
            <sales_total_cost>26</sales_total_cost>
            <product_actual_cost>22</product_actual_cost>
            <deviation>4</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>2</transaction_id>
            <store_id>1</store_id>
            <customer_id>1</customer_id>
            <product_id>2</product_id>
            <quantity>2</quantity>
            <sales_total_cost>48</sales_total_cost>
            <product_actual_cost>45</product_actual_cost>
            <deviation>3</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>3</transaction_id>
            <store_id>1</store_id>
            <customer_id>1</customer_id>
            <product_id>3</product_id>
            <quantity>3</quantity>
            <sales_total_cost>130.5</sales_total_cost>
            <product_actual_cost>126</product_actual_cost>
            <deviation>4.5</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>4</transaction_id>
            <store_id>1</store_id>
            <customer_id>2</customer_id>
            <product_id>3</product_id>
            <quantity>2</quantity>
            <sales_total_cost>87</sales_total_cost>
            <product_actual_cost>84</product_actual_cost>
            <deviation>3</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>5</transaction_id>
            <store_id>1</store_id>
            <customer_id>2</customer_id>
            <product_id>4</product_id>
            <quantity>6</quantity>
            <sales_total_cost>120</sales_total_cost>
            <product_actual_cost>108</product_actual_cost>
            <deviation>12</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>6</transaction_id>
            <store_id>1</store_id>
            <customer_id>3</customer_id>
            <product_id>2</product_id>
            <quantity>4</quantity>
            <sales_total_cost>26</sales_total_cost>
            <product_actual_cost>22</product_actual_cost>
            <deviation>4</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>7</transaction_id>
            <store_id>1</store_id>
            <customer_id>3</customer_id>
            <product_id>3</product_id>
            <quantity>1</quantity>
            <sales_total_cost>43.5</sales_total_cost>
            <product_actual_cost>42</product_actual_cost>
            <deviation>1.5</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>8</transaction_id>
            <store_id>1</store_id>
            <customer_id>3</customer_id>
            <product_id>4</product_id>
            <quantity>6</quantity>
            <sales_total_cost>120</sales_total_cost>
            <product_actual_cost>108</product_actual_cost>
            <deviation>12</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>9</transaction_id>
            <store_id>1</store_id>
            <customer_id>3</customer_id>
            <product_id>5</product_id>
            <quantity>2</quantity>
            <sales_total_cost>278</sales_total_cost>
            <product_actual_cost>270</product_actual_cost>
            <deviation>8</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>10</transaction_id>
            <store_id>2</store_id>
            <customer_id>1</customer_id>
            <product_id>4</product_id>
            <quantity>3</quantity>
            <sales_total_cost>60</sales_total_cost>
            <product_actual_cost>54</product_actual_cost>
            <deviation>6</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>11</transaction_id>
            <store_id>2</store_id>
            <customer_id>1</customer_id>
            <product_id>5</product_id>
            <quantity>1</quantity>
            <sales_total_cost>139</sales_total_cost>
            <product_actual_cost>135</product_actual_cost>
            <deviation>4</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>12</transaction_id>
            <store_id>1</store_id>
            <customer_id>1</customer_id>
            <product_id>4</product_id>
            <quantity>3</quantity>
            <sales_total_cost>60 </sales_total_cost>
            <product_actual_cost>54</product_actual_cost>
            <deviation>6</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>13</transaction_id>
            <store_id>1</store_id>
            <customer_id>2</customer_id>
            <product_id>2</product_id>
            <quantity>1</quantity>
            <sales_total_cost>24</sales_total_cost>
            <product_actual_cost>22.5</product_actual_cost>
            <deviation>1.50</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>14</transaction_id>
            <store_id>1</store_id>
            <customer_id>2</customer_id>
            <product_id>2</product_id>
            <quantity>2</quantity>
            <sales_total_cost>13</sales_total_cost>
            <product_actual_cost>11</product_actual_cost>
            <deviation>2</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>15</transaction_id>
            <store_id>1</store_id>
            <customer_id>3</customer_id>
            <product_id>1</product_id>
            <quantity>2</quantity>
            <sales_total_cost>24</sales_total_cost>
            <product_actual_cost>22.5</product_actual_cost>
            <deviation>1.5</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>16</transaction_id>
            <store_id>2</store_id>
            <customer_id>1</customer_id>
            <product_id>2</product_id>
            <quantity>1</quantity>
            <sales_total_cost>6.5</sales_total_cost>
            <product_actual_cost>5.5</product_actual_cost>
            <deviation>1</deviation>
        </ProductSale>

        <ProductSale>
            <transaction_id>17</transaction_id>
            <store_id>2</store_id>
            <customer_id>1</customer_id>
            <product_id>3</product_id>
            <quantity>1</quantity>
            <sales_total_cost>43.5</sales_total_cost>
            <product_actual_cost>42</product_actual_cost>
            <deviation>1.5</deviation>
        </ProductSale>



    </ProductSales-collection>

</FactProductSales>
